//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ContactoCliente = new HashSet<ContactoCliente>();
            this.Inmueble = new HashSet<Inmueble>();
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int IdCliente { get; set; }
        public string Nombre { get; set; }
        public string Telefono_1 { get; set; }
        public string Telefono_2 { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ContactoCliente> ContactoCliente { get; set; }
        public virtual ICollection<Inmueble> Inmueble { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
