//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoCliente
    {
        public int IdContactoCliente { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Area { get; set; }
        public string Cargo { get; set; }
        public string Celular { get; set; }
        public string Anexo { get; set; }
        public int IdCliente { get; set; }
        public bool Active { get; set; }
        public bool Default { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
