//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ESSACInspeccionesEntities : DbContext
    {
        public ESSACInspeccionesEntities()
            : base("name=ESSACInspeccionesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<ContactoCliente> ContactoCliente { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<EstadoProtocolo> EstadoProtocolo { get; set; }
        public DbSet<Inmueble> Inmueble { get; set; }
        public DbSet<OpcionRespuesta> OpcionRespuesta { get; set; }
        public DbSet<Plantilla> Plantilla { get; set; }
        public DbSet<Protocolo> Protocolo { get; set; }
        public DbSet<Respuesta> Respuesta { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Seccion> Seccion { get; set; }
        public DbSet<SeccionBody> SeccionBody { get; set; }
        public DbSet<Servicio> Servicio { get; set; }
        public DbSet<ServicioEstado> ServicioEstado { get; set; }
        public DbSet<TableHeader> TableHeader { get; set; }
        public DbSet<Tarea> Tarea { get; set; }
        public DbSet<TipoCelda> TipoCelda { get; set; }
        public DbSet<TipoSeccion> TipoSeccion { get; set; }
        public DbSet<TipoTag> TipoTag { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<SP_CountEstados_Result> SP_CountEstados(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin, Nullable<int> idResponsable)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var idResponsableParameter = idResponsable.HasValue ?
                new ObjectParameter("IdResponsable", idResponsable) :
                new ObjectParameter("IdResponsable", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CountEstados_Result>("SP_CountEstados", fechaInicioParameter, fechaFinParameter, idResponsableParameter);
        }
    
        public virtual ObjectResult<SP_GetPlantillas_Result> SP_GetPlantillas(Nullable<int> idUsuario, Nullable<int> idInmueble)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(int));
    
            var idInmuebleParameter = idInmueble.HasValue ?
                new ObjectParameter("IdInmueble", idInmueble) :
                new ObjectParameter("IdInmueble", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPlantillas_Result>("SP_GetPlantillas", idUsuarioParameter, idInmuebleParameter);
        }
    
        public virtual ObjectResult<SP_GetTareas_Result> SP_GetTareas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTareas_Result>("SP_GetTareas");
        }
    
        public virtual ObjectResult<SP_GetTareasResponsables_Result> SP_GetTareasResponsables(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("FechaInicio", fechaInicio) :
                new ObjectParameter("FechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTareasResponsables_Result>("SP_GetTareasResponsables", fechaInicioParameter, fechaFinParameter);
        }
    }
}
