//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodoProtocolo
    {
        public PeriodoProtocolo()
        {
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int IdPeriodoProtocolo { get; set; }
        public int IdPeriodo { get; set; }
        public int IdProtocolo { get; set; }
        public bool Active { get; set; }
    
        public virtual Periodo Periodo { get; set; }
        public virtual Protocolo Protocolo { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
