//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        public Plantilla()
        {
            this.Protocolo = new HashSet<Protocolo>();
            this.Seccion = new HashSet<Seccion>();
            this.Tarea = new HashSet<Tarea>();
            this.SeccionBody = new HashSet<SeccionBody>();
        }
    
        public int IdPlantilla { get; set; }
        public string Nombre { get; set; }
        public string Nombre2 { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Protocolo> Protocolo { get; set; }
        public virtual ICollection<Seccion> Seccion { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
        public virtual ICollection<SeccionBody> SeccionBody { get; set; }
    }
}
