//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocolo
    {
        public Protocolo()
        {
            this.Respuesta = new HashSet<Respuesta>();
        }
    
        public int IdProtocolo { get; set; }
        public int IdPlantilla { get; set; }
        public int IdInmueble { get; set; }
        public int IdEstado { get; set; }
        public string Codigo { get; set; }
        public string NombreAreaProtegida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Direccion { get; set; }
        public string TipoPrueba { get; set; }
        public bool Active { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int IdPeriodo { get; set; }
    
        public virtual EstadoProtocolo EstadoProtocolo { get; set; }
        public virtual Inmueble Inmueble { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Plantilla Plantilla { get; set; }
        public virtual ICollection<Respuesta> Respuesta { get; set; }
    }
}
