//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int IdProtocolo { get; set; }
        public int IdSeccionBody { get; set; }
        public string Descripcion { get; set; }
        public bool Active { get; set; }
    
        public virtual SeccionBody SeccionBody { get; set; }
        public virtual Protocolo Protocolo { get; set; }
    }
}
