//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeccionBody
    {
        public SeccionBody()
        {
            this.Respuesta = new HashSet<Respuesta>();
            this.Plantilla = new HashSet<Plantilla>();
        }
    
        public int IdSeccionBody { get; set; }
        public int IdSeccion { get; set; }
        public int IdTipoCelda { get; set; }
        public Nullable<int> IdTipoTag { get; set; }
        public string Descripcion { get; set; }
        public int Rowspan { get; set; }
        public int Colspan { get; set; }
        public bool BackgroundColor { get; set; }
        public int NumeroFila { get; set; }
        public int Orden { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Respuesta> Respuesta { get; set; }
        public virtual Seccion Seccion { get; set; }
        public virtual TipoCelda TipoCelda { get; set; }
        public virtual TipoTag TipoTag { get; set; }
        public virtual ICollection<Plantilla> Plantilla { get; set; }
    }
}
