//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seccion
    {
        public Seccion()
        {
            this.SeccionBody = new HashSet<SeccionBody>();
        }
    
        public int IdSeccion { get; set; }
        public Nullable<int> IdSeccionPadre { get; set; }
        public int IdPlantilla { get; set; }
        public string Nombre { get; set; }
        public int Pagina { get; set; }
        public int Orden { get; set; }
        public bool Active { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
        public virtual ICollection<SeccionBody> SeccionBody { get; set; }
    }
}
