//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioEstado
    {
        public int IdServicio { get; set; }
        public int IdEstado { get; set; }
        public bool Active { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
