//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableHeader
    {
        public int IdTableHeader { get; set; }
        public int IdSeccion { get; set; }
        public string Descripcion { get; set; }
        public int Rowspan { get; set; }
        public int Colspan { get; set; }
        public int NumeroFila { get; set; }
        public int Orden { get; set; }
        public bool Active { get; set; }
    }
}
