//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESSACInspecciones.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public Tarea()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int IdTarea { get; set; }
        public int IdCliente { get; set; }
        public int IdInmueble { get; set; }
        public Nullable<int> IdPlantilla { get; set; }
        public int IdServicio { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string Observaciones { get; set; }
        public bool Active { get; set; }
        public int IdEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Inmueble Inmueble { get; set; }
        public virtual Plantilla Plantilla { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
